### ISSUE TITLE
 We should be able to assign each activity to multiple clusters as it is nearly impossible to do that for each cluster manually.

### ISSUE THREAD

**Issue by manishadk** [naxadeve/mes-core#170]
We should be able to assign each activity to multiple clusters as it is nearly
impossible to do that for each cluster manually.

Inside any assign page , going through a single cluster, maybe add a checkbox at the top which selects all the activities and then user can save at once

**Comment by SanipRijal** [comment]
It will be easier to implement if we can get the design functionality for this.
