### ISSUE TITLE
API : Benificiary list

### ISSUE THREAD

**Issue by hereyubaraj** [naxadeve/mes-core#7]
@manishadk @awemulya @varun2948 
Question : Do the benificiary belongs to all the activity group ? 

<img width="1106" alt="Screenshot 2019-03-19 11 13 46" src="https://user-images.githubusercontent.com/47551530/54582239-1c019300-4a38-11e9-88db-0d9e64a299e7.png">

**Comment by awemulya** [comment]
Benificaty belongs to project.
